.uno/CodeCompletion/ux13/MainView.g.uno
.uno/CodeCompletion/ux13/Manna.Border.g.uno
.uno/CodeCompletion/ux13/Manna.Button.g.uno
.uno/CodeCompletion/ux13/Manna.Card.g.uno
.uno/CodeCompletion/ux13/ContactUsPage.g.uno
.uno/CodeCompletion/ux13/HomePage.g.uno
.uno/CodeCompletion/ux13/MenuPage.g.uno
.uno/CodeCompletion/ux13/SplashPage.g.uno
.uno/CodeCompletion/ux13/Manna.unoproj.g.uno